- .firebaserc
- firebase.json
* Update project ID
* Fix hosting target.
> Fix Firebase information.

- src/components/EditQuestion.tsx
- src/components/EditQuiz.tsx
* Answer editing needs to be changed to support ordering and correctness changes.
> Update answer editing.

- src/components/EditQuestion.tsx
* Allows admin panel to edit question correctness.
> Update UI on correctness changes.

- .firebaserc
- .github/workflows/hosting-dev.yml
- public/index.html
- src/components/EditQuestion.tsx
- src/components/EditQuiz.tsx
- src/components/IonRowCol.tsx
- src/components/MultiEdit.tsx
- src/components/MultiScore.tsx
- src/pages/Quiz.tsx
- src/theme/quill.css
- src/types/quiz.ts
Brings `master` code in line with `dev`.
- Adds new `master` C/I
- Fixes answer and header handling in.
> Merge latest development code into master.

- .github/workflows/hosting-dev.yml
* Use all development environmental variables instead of just the backend URL.
> Fix firebase configuration in C/I.

- src/components/EditQuestion.tsx
- src/components/EditQuiz.tsx
- src/components/EditQuizInfo.tsx
- src/components/EditRaffle.tsx
- src/components/EditTerms.tsx
- src/components/ErrorContent.tsx
- src/components/MultiEdit.tsx
- src/components/MultiScore.tsx
- src/pages/CurrentRaffle.tsx
- src/pages/Emails.tsx
- src/pages/Home.tsx
- Display current raffle.
- Create new raffle if none exists.
- Update tab icons to match actions.
> Add initial raffle manager.

- src/components/EditQuestion.tsx
- src/components/EditQuiz.tsx
- Fix bug where answer deletion attempted to save a question data to an answer ID (additional safeguards now in place in the backend for these issues)
- Update question views when required.
> Fix answer deletion and question view updating.

- src/components/EditQuestion.tsx
- src/components/EditQuiz.tsx
- src/components/EditQuizInfo.tsx
- src/components/EditRaffle.tsx
- src/components/EditTerms.tsx
- src/components/ErrorContent.tsx
- src/pages/Admins.tsx
- src/pages/Emails.tsx
- src/pages/Home.tsx
- Adds refresh button for data loading errors.
- Adds admin page with list, add, and delete functionality.
> Add admin page and data refresh.

- .github/workflows/hosting-dev.yml
- .github/workflows/hosting.yml
- functions/index.js
- src/components/EditRaffle.tsx
* Add raffle winner selection
* Add raffle download
* Add historical raffle view
* Update CI to handle functions
> Add raffle management and update CI.

- .github/workflows/hosting-dev.yml
- .github/workflows/hosting.yml
* Ensure function dependencies are installed during C/I builds.
> Install function dependencies in C/I build.

- .github/workflows/hosting-dev.yml
- .github/workflows/hosting.yml
* Ensure function assets also get archived.
> Archive function assets in addition to build.

- .github/workflows/hosting-dev.yml
- .github/workflows/hosting.yml
Reverts Get-Your-GreenBack-Tompkins/gygb-admin-web#27
> Revert "Archive function assets in addition to build."

- .github/workflows/hosting-dev.yml
- .github/workflows/hosting.yml
Reverts Get-Your-GreenBack-Tompkins/gygb-admin-web#26
> Revert "Install function dependencies in C/I build."

- .github/workflows/hosting-dev.yml
- .github/workflows/hosting.yml
> Revert functions deploy.

- src/components/EditRaffle.tsx
> Fix raffle creation endpoint path.

- src/components/EditQuestion.tsx
- src/components/EditRaffle.tsx
> Merge final tweaks into production.

- src/components/EditQuestion.tsx
- src/components/EditQuiz.tsx
- src/components/EditQuizInfo.tsx
- src/components/EditRaffle.tsx
- src/components/EditTerms.tsx
- src/components/MultiEdit.tsx
- src/components/MultiScore.tsx
- src/pages/Emails.tsx
- src/util/index.ts
* Fix raffle creation issues.
* Offer sanity checks.
* Fix rich text formatting.
> Release development into production.

- .prettierrc.js
- src/components/EditTerms.tsx
Tested in development frontend and backend and is ready for release.
> Release terms and condition editor changes into production.

- src/components/EditTerms.tsx
* The POST is now `link` not `text`.
> Fix link editing!

- functions/package-lock.json
- src/components/EditQuizInfo.tsx
- src/components/EditTerms.tsx
> Move raffle editing, link editing fixes, and dependency updates into production.
